name: python-fortran
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - setuptools
  - numpy
  - matplotlib
  - scipy
  - cython
  - sympy
  - pandas
  - fortran-magic 
  - cython 
  - numba
  - tqdm
  - imageio
  - pillow
  - pythran
  - pip
  - pip:
     - julia
